### ISSUE TITLE
Separate dictionary to list samples for BDT training

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-multilepton#10]
Prefer powheg samples over MG; LO over NLO.

**Comment by ktht** [comment]
I went through [the list of backround samples](https://github.com/HEP-KBFI/tth-nanoAOD/blob/master/test/datasets/json/datasets.json) that we've processed thus far an looked for the samples that are disabled by default but could potentially replace amcatnlo samples. So I came up with this list:

https://github.com/HEP-KBFI/hh-multilepton/blob/826c48c226b89aa21921c70fba7993f34c7b58e3/python/samples/hhAnalyzeSamples_2016_BDT.py#L1-L16

Here we enable LO DY and W+jets samples binned by jet multiplicity and HT, a WZTo3LNu powheg sample and LO ttV samples that are othewise disabled in the main analysis and hence would not need the odd-even treatment of BDT training in principle. The samples are picked up only when it's run in `forBDTtraining` mode, like for instance here (note the suffix argument):

https://github.com/HEP-KBFI/hh-multilepton/blob/826c48c226b89aa21921c70fba7993f34c7b58e3/test/hhAnalyzeRun_0l_4tau.py#L110

**Comment by veelken** [comment]
Hi Karl, 

sorry, can you remind me which DY samples we decided to use for the BDT training: NLO inclusive, NLO binned in Njet, or LO ? I see no reason that would stop us from using NLO inclusive + LO inclusive + LO binned in Njet and HT.

**Comment by ktht** [comment]
The idea was to avoid negative weights in the training, which motivates the usage of LO samples because the NLO samples are generated with aMC@NLO which produces events with negative weights.

**Comment by ktht** [comment]
FYI: https://github.com/HEP-KBFI/hh-bbww/issues/9#issuecomment-653883827
