### ISSUE TITLE
Reprocess signal_ggf_nonresonant_node_(4|5)_hh_4v from 2017 era

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-multilepton#13]
The (single files from the) samples look to be corrupted. Will disable the files temporarily and reprocess the sample again. ETA tomorrow.

**Comment by kramerto** [comment]
/hdfs/local/karl/ttHNtupleProduction/2017/2020Apr15_wPresel_nom_all/ntuples/ZZTo4L_ext2/0000/tree_33.root seems to be affected by this as well

**Comment by ktht** [comment]
Will reprocess the file tomorrow, ETA the day after.

**Comment by rdewanje** [comment]
/hdfs/local/karl/ttHNtupleProduction/2018/2020Jul15_woPresel_nom_all/ntuples/ST_t-channel_top_4f_inclusiveDecays/0000/tree_442.root is the file affected in 2018 era.

**Comment by ktht** [comment]
I'll wait a bit with reprocessing, because some corrupted files may eventually be recovered soon.
@rdewanje you can blacklist the file yourself in the sample dictionary.

**Comment by rdewanje** [comment]
How do we blacklist specific files in the sample dictionary for a given sample ? By just giving the tree numbers in the ("blacklist", []) part of the OD for that sample ?e.g. ("blacklist", [442]) to skip "tree_442.root" for the Single top sample above ?

**Comment by ktht** [comment]
The corrupted files seem to have recovered -> no reason to reprocess and blacklist them anymore. In case you still see that some files produce IO errors, reopen this thread or create a new one.

@rdewanje yes, for the entry that has `ST_t-channel_top_4f_inclusiveDecays` value for `process_name_specific` key in `tthAnalyzeRun_2017_base.py` file. But the file should be recovered by now.
