### ISSUE TITLE
New signal samples

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-multilepton#19]
As discussed last Friday, there are new signal samples available which we haven't yet processed. Some of the new samples just increase the statistics of the phase space that's already been covered by the existing samples:
- privately produced non-resonant 2017 samples;
- spin-0 4tau sample @ M=450 GeV;
- all 2017 resonant samples @ M=1TeV.

The availability of the samples (not the availability in our FW) is shown here:
- [2016 era](https://kaehatah.web.cern.ch/coverage_hh_multilepton_RunIISummer16MiniAODv3.html);
- [2017 era](https://kaehatah.web.cern.ch/coverage_hh_multilepton_RunIIFall17MiniAODv2.html);
- [2018 era](https://kaehatah.web.cern.ch/coverage_hh_multilepton_RunIIAutumn18MiniAOD.html);
- [full Run 2](https://kaehatah.web.cern.ch/coverage_hh_multilepton.html).

Many samples are still in production, which is why I'm holding off the Ntuple production until most of them are finished:
- `/GluGluToHHTo4Tau_node_cHHH0_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v1/MINIAODSIM` ([15%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-02734))
- `/GluGluToHHTo4Tau_node_cHHH1_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v1/MINIAODSIM` ([20%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-02733))
- `/GluGluToHHTo4Tau_node_cHHH2p45_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v1/MINIAODSIM` ([20%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-02736))
- `/GluGluToHHTo4Tau_node_cHHH5_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v1/MINIAODSIM` ([40%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-02735))
- `/GluGluToHHTo2V2tau_node_1_TuneCP5_PSWeights_13TeV-madgraph-pythia8_correctedcfg/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([90%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04731))
- `/GluGluToHHTo4Tau_node_10_TuneCP5_PSWeights_13TeV-madgraph-pythia8_correctedcfg/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([56%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04804))
- `/GluGluToBulkGravitonToHHTo2V2tau_M-2000_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([1%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04976))
- `/GluGluToBulkGravitonToHHTo4V_M-1000_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([31%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04958))
- `/GluGluToBulkGravitonToHHTo4V_M-1250_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([64%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04959))
- `/GluGluToBulkGravitonToHHTo4V_M-2000_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([44%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04962))
- `/GluGluToBulkGravitonToHHTo4tau_M-1250_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([24%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04987))
- `/GluGluToRadionToHHTo4V_M-1250_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM` ([79%](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04952))
- `/GluGluToBulkGravitonToHHTo4V_M-850_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM` ([100%?](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall18wmLHEGS-03623))

**Comment by ktht** [comment]
Queried the DAS this weekend and found more samples in 2016 (see [this table](https://kaehatah.web.cern.ch/coverage_hh_multilepton_RunIISummer16MiniAODv3.html)), albeit most of the new samples are still marked as in "production".

**Comment by tolange** [comment]
Hi Karl, it seems like all our HP requested samples are in production now as well as a few of the others. Since some of the lower priority samples are growing as well (having all the same priority) I would hope that the other remaining samples will show up too in the next days. (Its somewhat funny that the HP request we worked for a while in the end has bought us only a few days..)

**Comment by ktht** [comment]
Here's the current status (but also check the links in the initial post to get a better idea of what's going on):
- all NLO ggF samples available
  - 5 samples from 2016 still in production
- we migrate to dipoleRecoilOff non-resonant VBF samples
  - all samples available, except for cv = c2v = c3 = 1 sample from 2016 for 4tau (but it's been requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-04599))
  - 9 samples from 2016, 5 samples from 2017, 1 sample from 2018 still in production
- all LO ggF samples available
  - except for node 1 in 4tau and node 6 in 2v2tau in 2016 (but only node 6 seems to be requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-04640))
- there are no overlapping samples, except for resonant ggF samples
  - spin-0 and spin-2 in 2016: statistics of every mass point doubled by two sets of samples (with and without the tune ID in the DBS name)
  - mass point of 1 TeV doubled in 2017 spin-0 and spin-2 case: two sets of samples (with and without the tune ID in the DBS name), overlapping at this one mass point;
- no resonant VBF samples, except in 2018 4tau and 2v2tau;
- mass points 340 and 1200 missing more often than not, so ignoring those:
  - 2016 resonant samples missing:
    - spin-2 ggF sample for 4v at 320 GeV (already requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-04414));
    - spin-0 ggF sample for 2v2tau at 600 GeV (already requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-04495));
    - spin-0 ggF sample for 4tau at 2000 GeV (already requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-04456));
    - spin-2 ggF sample for 4tau at 2500 GeV (already requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer15wmLHEGS-04482));
  - 2017 resonant samples missing only spin-0 ggF sample for 4tau at 1500 GeV (already requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-04981));
  - 2018 resonant samples missing:
    - spin-2 ggF sample for 4v at 1750 GeV (already requested: [link](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall18wmLHEGS-03920));
    - spin-0 VBF sample for 4tau and 2v2tau at 2500 GeV (no request ID found either);
- many samples still in production (excluding the samples which have been requested but the production of which hasn't started yet);
  - 70 in 2016;
  - 10 in 2017;
  - 1 in 2018.

I'll start Ntuple production today/tomorrow, of the samples that are currently valid (and not in production).

**Comment by ktht** [comment]
The `run` and `luminosityBlock` branches need to be rewritten in Ntuples that are produced from private MiniAOD files because they the same run, lumi and event numbers are exactly the same in every file (1:1:[1..250]). Not sure, if nanoAOD-tools can straight up replace the branch contents, though, but the new run number can be associated with ROOT file name (eg run number is 15 if the file name is tree_15.root), and lumi number can be taken as event idx / 250. If we don't do that, then certain validation procedures (executed in every workflow) that rely on the uniqueness of run, lumi and event numbers will no longer be functional.

**Comment by ktht** [comment]
Current status:
| Era  | Requested | MiniAODs (in PROD+TAPE) | Ntupelizing | Ntupelized | Post-processed\* |
| :--: | :-------: | :---------------------: | :---------: | :--------: | :--------------: |
| 2016 |    257    |   257 (19+1)            |      6      |    231     |      49          |
| 2017 |    243    |   243    (2)            |      0      |    241     |     156          |
| 2018 |    323    |   322  (0+1)            |      1      |    320     |     318          |

\* All Ntuples need to be post-processed again, some samples will be replaced.

**Comment by ktht** [comment]
Need to post-process the privately produced samples again because I made a mistake when trying to assign a new lumi number. The current run:lumi:event numbers are not unique which is a problem.
