### ISSUE TITLE
Reintroduce single H decay splitting for tH

### ISSUE THREAD

**Issue by tolange** [HEP-KBFI/hh-multilepton#27]
It seems like tH is not spliced by decay mode anymore. Have not checked yet however at which point -> In the addSystFakeRate.root they are not spliced anymore.

**Comment by tolange** [comment]
ok the problem was somewhere else, please ignore this issue

**Comment by ktht** [comment]
Looks like Christian already fixed the problem in e995fe21e7564a8b8de424af580894574213dfd0. If you agree then please close the issue.
