### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by tolange** [HEP-KBFI/hh-multilepton#29]
Currently I don't see the tau shape uncertainty for the LO signal entries anymore. -> Currently removed from Datacard evaluation -> check again after the status update.

**Comment by ktht** [comment]
Is it still an issue?

**Comment by tolange** [comment]
I think this was one of the samples where those are not available-> I will close this issue

**Comment by tolange** [comment]
This is not relevant anymore i guess
