### ISSUE TITLE
Suspicious value in kt scan file

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-multilepton#4]
Shouldn't it be 0.8(3) or something?
https://github.com/HEP-KBFI/hh-multilepton/blob/e2e49b41e46c52566bba1c54238750fa70437048/data/kt_scan.dat#L26

**Comment by acarvalh** [comment]
Fixed.
Also fixed the normalization to 1.0
https://github.com/HEP-KBFI/hh-multilepton/commit/d87ad8450aad91026003636bfcc9f18115d464cb
